version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: mcp-test-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native protocol port
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: ""
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/?query=SELECT%201"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  clickhouse_data:
  clickhouse_logs: